name: Dr. ViKi DevOps Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Test application
      run: |
        python app.py &
        sleep 5
        curl -f http://localhost:8080/health || exit 1
        pkill -f "python app.py"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t drviki-app .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8080:8080 --name test-container drviki-app
        sleep 10
        curl -f http://localhost:8080/health || exit 1
        docker stop test-container
        docker rm test-container
    
    - name: Run security scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:latest image drviki-app

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Update system and install Docker if needed
          sudo yum update -y
          sudo yum install -y docker git
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -a -G docker $USER
          
          # Clone/update repository
          cd /home/${{ secrets.EC2_USER }}
          if [ -d "doctor-viki-app" ]; then
            cd doctor-viki-app
            git pull origin main
          else
            git clone https://github.com/${{ github.repository }}.git doctor-viki-app
            cd doctor-viki-app
          fi
          
          # Stop existing container
          sudo docker stop drviki-app || true
          sudo docker rm drviki-app || true
          
          # Build and run new container
          sudo docker build -t drviki-app .
          sudo docker run -d --name drviki-app -p 80:8080 --restart unless-stopped drviki-app
          
          # Verify deployment
          sleep 10
          curl -f http://localhost/health || exit 1